name: 'JSON to Variables Setter'
description: 'Parse JSON file and set GitHub Actions outputs'
inputs:
  json-file:
    description: 'Path to the JSON file'
    required: true
    default: '.github/workflows/python_project_matrix.json'
outputs:
  os:
    description: 'List of operating systems'
    value: ${{ steps.set_outputs.outputs.os }}
  python_versions:
    description: 'List of Python versions'
    value: ${{ steps.set_outputs.outputs.python_versions }}
  ghpages_branch:
    description: 'GitHub Pages branch'
    value: ${{ steps.set_outputs.outputs.ghpages_branch }}
  # For future additions
  #custom_custom_param:
  #  description: 'Custom parameter'
  #  value: ${{ steps.set_outputs.outputs.custom_custom_param }}
  #custom_custom_param_list:
  #  description: 'List of Custom parameter'
  #  value: ${{ steps.set_outputs.outputs.custom_custom_param_list }}
  #custom_custom_param_list_0:
  #  description: 'custom_param_list[0]'
  #  value: ${{ steps.set_outputs.outputs.custom_custom_param_list_0 }}
  #custom_custom_nested_nested_key1:
  #  description: 'Nested custom key 1'
  #  value: ${{ steps.set_outputs.outputs.custom_custom_nested_nested_key1 }}
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5.2.0
      with:
        python-version: '3.12'

    - name: Parse JSON and set outputs
      id: set_outputs
      shell: bash
      run: |
        python .github/workflows/scripts/json_to_github_output.py ${{ inputs.json-file }}
      env:
        GITHUB_OUTPUT: $GITHUB_OUTPUT
