name: 'JSON to Variables Setter'
description: 'Parse JSON file and set GitHub Actions outputs'
inputs:
  json-file:
    description: 'Path to the JSON file'
    required: true
    default: '.github/workflows/python_project_matrix.json'
outputs:
  os:
    description: 'List of operating systems'
  python_versions:
    description: 'List of Python versions'
  ghpages_branch:
    description: 'GitHub Pages branch'
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5.2.0
      with:
        python-version: '3.12'

    - name: Parse JSON and set outputs
      id: parse_json
      run: |
        python .github/actions/json2vars-setter/scripts/json_to_github_output.py ${{ inputs.json-file }}
        # Read from GITHUB_OUTPUT and set the outputs
        while IFS= read -r line; do
          key=$(echo "$line" | cut -d'=' -f1)
          value=$(echo "$line" | cut -d'=' -f2-)
          echo "$key=$value" >> $GITHUB_OUTPUT
        done < "$GITHUB_OUTPUT"
      env:
        GITHUB_OUTPUT: $GITHUB_OUTPUT
