name: 'Send Payload to Pytest Testmon'
description: 'Dynamically build and send dispatch payload to trigger pytest testmon tests across multiple OS and Python versions'

inputs:
  # ペイロードの生成条件
  #  - required: true の場合は環境変数の設定が必須
  #  - required: false の場合は環境変数の設定は不要だが、設定した場合はその値でペイロード生成処理に渡る
  repository_name:
    description: 'Repository name'
    required: true
    default: '7rikazhexde/python-project-sandbox'
  ghpages_branch:
    description: 'Target branch to fetch testmon data from'
    required: false
    default: 'gh_pages'
  os_list:
    description: 'Space-separated list of OS to run tests on'
    required: true
    default: 'ubuntu-latest macos-13 windows-latest'
  python_versions:
    description: 'Space-separated list of Python versions to test'
    required: true
    default: '3.11 3.12'
  custom_param:
    description: 'An optional custom parameter for additional configuration'
    required: false
    #default: 'default_value'
    default: 'custom_param_test_val'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5.2.0
      with:
        python-version: '3.12'

    - name: Run Python script
      run: |
        python3 .github/send_payload.py
      shell: bash
      env:
        REPOSITORY_NAME: ${{ inputs.repository_name }}
        # GHPAGES_BRANCH: ${{ inputs.ghpages_branch }} # 省略可能
        OS_LIST: ${{ inputs.os_list }}
        PYTHON_VERSIONS: ${{ inputs.python_versions }}
        CUSTOM_PARAM: ${{ inputs.custom_param }} # 省略可能
