name: Check GitHub API Rate Limits
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  check_rate_limits:
    runs-on: ubuntu-latest
    steps:
      - name: Check GitHub API Rate Limits
        run: |
          echo "=== GitHub API Rate Limits with Token ==="
          curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/rate_limit | jq '.rate'

          echo -e "\n=== Search API Rate Limits with Token ==="
          curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/rate_limit | jq '.resources.search'

          echo -e "\n=== GraphQL API Rate Limits with Token ==="
          curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/rate_limit | jq '.resources.graphql'

          echo -e "\n=== GitHub API Rate Limits without Token ==="
          curl -s https://api.github.com/rate_limit | jq '.rate'

          echo -e "\n=== Search API Rate Limits without Token ==="
          curl -s https://api.github.com/rate_limit | jq '.resources.search'

          echo -e "\n=== GraphQL API Rate Limits without Token ==="
          curl -s https://api.github.com/rate_limit | jq '.resources.graphql'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
